=== nzzdev/Q-poll-result/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Umfrageresultat",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string",
      "Q:options": {
        "placeholder": "Der Titel bringt die Kernaussage der Umfrageresultate auf den Punkt&#46;"
      }
    },
    "subtitle": {
      "title": "Untertitel",
      "type": "string",
      "Q:options": {
        "placeholder": "Stimmabsichten zur XY-Vorlage"
      }
    },
    "polls": {
      "title": "Umfragen",
      "type": "array",
      "Q:options": {
        "expandable": {
          "itemLabelProperty": "date"
        },
        "notificationChecks": [
          {
            "type": "ToolEndpoint",
            "config": {
              "endpoint": "notification/pollTotalOverOneHundredPercent",
              "fields": ["polls"]
            },
            "priority": {
              "type": "high",
              "value": 0
            }
          }
        ]
      },
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/preVoteNoToYes5" },
          { "$ref": "#/definitions/preVoteNoToYes3" }
        ]
      }
    },
    "notes": {
      "type": "string",
      "title": "Bemerkungen"
    },
    "sources": {
      "type": "array",
      "title": "Quellen",
      "items": {
        "title": "Quelle",
        "type": "object",
        "properties": {
          "text": {
            "title": "Text",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "Q:options": {
              "placeholder": "Direktlink zur Quelle, http&#53;//&#46;&#46;&#46;"
            },
            "properties": {
              "url": {
                "title": "Url",
                "type": "string"
              },
              "isValid": {
                "type": "boolean"
              }
            }
          }
        },
        "required": ["text"]
      }
    }
  },
  "required": ["title"],
  "definitions": {
    "preVoteNoToYes5": {
      "type": "object",
      "title": "Umfrageergebnis mit 5 Positionen",
      "properties": {
        "type": {
          "type": "string",
          "default": "preVoteNoToYes5",
          "enum": ["preVoteNoToYes5"],
          "Q:options": {
            "hideInEditor": true
          }
        },
        "date": {
          "type": "string",
          "title": "Datum",
          "Q:type": "date"
        },
        "answers": {
          "type": "object",
          "title": "Antworten (in Prozent)",
          "properties": {
            "certain-yes": {
              "type": "number",
              "title": "bestimmt dafür"
            },
            "rather-yes": {
              "type": "number",
              "title": "eher dafür"
            },
            "undecided": {
              "type": "number",
              "title": "weiss nicht"
            },
            "rather-no": {
              "type": "number",
              "title": "eher dagegen"
            },
            "certain-no": {
              "type": "number",
              "title": "bestimmt dagegen"
            }
          }
        }
      },
      "required": ["date"]
    },
    "preVoteNoToYes3": {
      "type": "object",
      "title": "Umfrageergebnis mit 3 Positionen",
      "properties": {
        "type": {
          "type": "string",
          "default": "preVoteNoToYes3",
          "enum": ["preVoteNoToYes3"],
          "Q:options": {
            "hideInEditor": true
          }
        },
        "date": {
          "type": "string",
          "title": "Datum",
          "Q:type": "date"
        },
        "answers": {
          "type": "object",
          "title": "Antworten (in Prozent)",
          "properties": {
            "yes": {
              "type": "number",
              "title": "bestimmt/eher dafür"
            },
            "undecided": {
              "type": "number",
              "title": "weiss nicht"
            },
            "no": {
              "type": "number",
              "title": "bestimmt/eher dagegen"
            }
          }
        }
      },
      "required": ["date"]
    }
  }
}

=== nzzdev/Q-poll-result/resources/fixtures/data/result.json
{
  "title": "FIXTURE: Stimmabsichten' zur Milchkuh-Initiative",
  "polls": [
    {
      "type": "preVoteNoToYes5",
      "date": "2016-04-29",
      "answers": {
        "certain-yes": 21,
        "rather-yes": 21,
        "undecided": 11,
        "rather-no": 19,
        "certain-no": 28
      }
    },
    {
      "type": "preVoteNoToYes5",
      "date": "2016-05-25",
      "answers": {
        "certain-yes": 22,
        "rather-yes": 18,
        "undecided": 11,
        "rather-no": 17,
        "certain-no": 32
      }
    },
    {
      "type": "preVoteNoToYes3",
      "date": "2016-05-25",
      "answers": {
        "yes": 22,
        "undecided": 11,
        "no": 67
      }
    }
  ],
  "notes": "Bei allen ausgewiesenen Zahlen ist bei einer 95-prozentigen Wahrscheinlichkeit ein statistischer Unsicherheitsbereich von rund 2.7 Prozentpunkten plus/minus mitzudenken (2.9 bei der 1. Umfrage).",
  "sources": [{
    "text": "NZZ Storytelling",
    "link": {
      "url": "https://nzz.ch/storytelling",
      "isValid": true
    }
  }]
}

=== nzzdev/Q-poll-result/resources/fixtures/data/spacing-text.json
{
  "title": "FIXTURE: spacings",
  "polls": [
    {
      "type": "preVoteNoToYes5",
      "answers": {
        "certain-yes": 50,
        "rather-yes": 16,
        "undecided": 1,
        "rather-no": 8,
        "certain-no": 25
      },
      "date": "2019-03-29"
    },
    {
      "type": "preVoteNoToYes5",
      "answers": {
        "certain-yes": 52,
        "rather-yes": 13,
        "undecided": 1,
        "rather-no": 8,
        "certain-no": 26
      },
      "date": "2019-04-27"
    }
  ],
  "sources": [
    {
      "link": {},
      "text": "SRG-Trend / GfS Bern"
    }
  ],
  "subtitle": "Trendumfrage des Forschungsinstituts GfS Bern zur neuen EU-Waffenrichtlinie",
  "notes": "Abstimmung vom 19. Mai 2019 im Trend, 1. Welle, 25. März bis 4. April 2019 (n = 5015). 2. Welle, 23. April bis 30. April 2019 (n = 5817). Der statistische Fehlerbereich beträgt ±2,7 Prozentpunkte."
}

=== nzzdev/Q-poll-result/resources/fixtures/data/only-3-not-sorted-one-not-100.json
{
  "title": "FIXTURE: only 3 positions - one < 100% - not sorted by date",
  "polls": [
    {
      "type": "preVoteNoToYes3",
      "date": "2016-05-25",
      "answers": {
        "yes": 22,
        "undecided": 11,
        "no": 67
      }
    },
    {
      "type": "preVoteNoToYes3",
      "date": "2016-04-29",
      "answers": {
        "yes": 22,
        "undecided": 11,
        "no": 67
      }
    },
    {
      "type": "preVoteNoToYes3",
      "date": "2016-06-25",
      "answers": {
        "yes": 22,
        "undecided": 11,
        "no": 12
      }
    }
  ],
  "notes":
    "Bei allen ausgewiesenen Zahlen ist bei einer 95-prozentigen Wahrscheinlichkeit ein statistischer Unsicherheitsbereich von rund 2.7 Prozentpunkten plus/minus mitzudenken (2.9 bei der 1. Umfrage).",
  "sources": [
    {
      "text": "NZZ Storytelling",
      "link": {
        "url": "https://nzz.ch/storytelling",
        "isValid": true
      }
    }
  ]
}

=== nzzdev/Q-poll-result/resources/fixtures/data/validation-msg-over-100-percent.json
{
  "title": "FIXTURE: Validation Error Message - Over 100%",
  "polls": [
    {
      "type": "preVoteNoToYes3",
      "date": "2016-06-25",
      "answers": {
        "yes": 22,
        "undecided": 11,
        "no": 68
      }
    }
  ],
  "notes": "Bei allen ausgewiesenen Zahlen ist bei einer 95-prozentigen Wahrscheinlichkeit ein statistischer Unsicherheitsbereich von rund 2.7 Prozentpunkten plus/minus mitzudenken (2.9 bei der 1. Umfrage).",
  "sources": [
    {
      "text": "NZZ Storytelling",
      "link": {
        "url": "https://nzz.ch/storytelling",
        "isValid": true
      }
    }
  ]
}
